---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]
  customize:
    memory: 2048

provisioner:
  require_chef_omnibus: true
  name: chef_solo
  environments_path: test/integration/environments
  client_rb:
    environment: dev
  attributes:
    openssh:
      server:
        permit_root_login: 'no'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: centos-6.6
    run_list:
    - recipe[yum]
  - name: centos-7.0
    run_list:
    - recipe[yum]
  - name: debian-7.8
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.10
    run_list:
    - recipe[apt]

suites:
  - name: default
    sudo: true
    run_list:
    - recipe[paramount]
    - recipe[test]
    - recipe[test::email]

